### PR TITLE
Make error handling work for errors throw in deeply nested JS function calls.

### LINKED ISSUE #613: Strange "can't read property webppl" error msg with wrong data type in inference args
When you (incorrectly) write the samples arg in inference opts as a string, you get:

```
Cannot read property 'webppl' of undefined
```

Minimal example

```
Infer({method: 'MCMC', samples: '5000'}, function(){return flip(0.5)});
```

### PR DESCRIPTION
**Pull request by null-a**
Closes #613.

### CODE REVIEW

File: src/errors/errors.js [hunk 1]
```diff
@@ -54,14 +54,18 @@ function filterJsStackTrace(stackTrace) {
...
+
   // We can only ever take the top-most webppl frame as any earlier
   // frames may have been generated on a different execution path.
   // (And besides, there should only be one entry as the JS stack is
   // cleared between each webppl function application.)
 
   var ix = _.findIndex(stackTrace, _.matcher({webppl: true}));
-  assert.ok(ix !== undefined, 'Expected to find wppl entry in JS stack trace.');
-  return stackTrace.slice(0, ix).concat(stackTrace[ix]);
+  return (ix >= 0) ? stackTrace.slice(0, ix).concat(stackTrace[ix]) : stackTrace;
```
Comment (stuhlmueller) [inline src/errors/errors.js]: Why not `stackTrace.slice(0, ix+1)` instead of `stackTrace.slice(0, ix).concat(stackTrace[ix])`?

Comment (null-a) [inline src/errors/errors.js]: No good reason! Changed now.
